version: "3.8"

services:
  agri-farms-db:
    image: postgres:16
    container_name: agri-farms-postgres
    environment:
      POSTGRES_DB: agrifarms
      POSTGRES_USER: agrifarms
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
